import{a as y,i as m,S as L}from"./assets/vendor-a595d5bb.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const b="43838744-76530a55bebff011fa4d493be",w="https://pixabay.com/api/",f=async(t,s=1,l=15)=>{try{return(await y.get(w,{params:{key:b,q:t,image_type:"photo",per_page:l,page:s}})).data}catch(o){throw m.error({title:"Error",message:"Failed to fetch images. Please try again later."}),o}};function g(t,s){const l=t.map(e=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <div class="full-image">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
          <ul class="image-button">
            <li><p>Likes</p><p>${e.likes}</p></li>
            <li><p>Views</p><p>${e.views}</p></li>
            <li><p>Comments</p><p>${e.comments}</p></li>
            <li><p>Downloads</p><p>${e.downloads}</p></li>
          </ul>
        </div>
      </a>
    </li>
  `).join("");s.insertAdjacentHTML("beforeend",l),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function n(t,s){m[s]({message:t,messageColor:"white",position:"topRight",backgroundColor:s==="error"?"red":"green"})}const v=document.querySelector("form"),h=document.querySelector(".gallery"),a=document.querySelector(".spinner"),i=document.querySelector(".load-button");let c=1,p=15,d="";i.classList.add("is-hidden");a.classList.add("is-hidden");v.addEventListener("submit",async t=>{if(t.preventDefault(),h.innerHTML="",c=1,d=t.target.elements.search_input.value.trim(),d===""){n("Please enter a search term.","warning");return}a.classList.remove("is-hidden"),i.classList.add("is-hidden");try{const s=await f(d,c,p);if(a.classList.add("is-hidden"),s.total===0){n("Sorry, there are no images matching your search query. Please try again!","error");return}g(s.hits,h),s.totalHits>p?i.classList.remove("is-hidden"):i.classList.add("is-hidden")}catch{a.classList.add("is-hidden"),n("An error occurred while fetching images. Please try again later.","error")}finally{t.target.reset()}});i.addEventListener("click",async()=>{try{c+=1,a.classList.remove("is-hidden"),i.classList.add("is-hidden");const t=await f(d,c,p);if(a.classList.add("is-hidden"),t.hits.length===0){n("No more images to load.","info"),i.classList.add("is-hidden");return}g(t.hits,h),c*p>=t.totalHits?i.classList.add("is-hidden"):i.classList.remove("is-hidden")}catch{a.classList.add("is-hidden"),n("An error occurred while fetching images. Please try again later.","error")}});
//# sourceMappingURL=commonHelpers.js.map
